CREATE TABLE IF NOT EXISTS customer_memory (
	user_id VARCHAR(128) PRIMARY KEY,
	payload TEXT NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer_approval_task (
	id VARCHAR(128) PRIMARY KEY,
	action_type VARCHAR(64) NOT NULL,
	conversation_id VARCHAR(160) NOT NULL,
	status VARCHAR(32) NOT NULL,
	payload TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operation_audit_event (
	id VARCHAR(128) PRIMARY KEY,
	user_id VARCHAR(128),
	action VARCHAR(128) NOT NULL,
	target VARCHAR(256),
	success BOOLEAN NOT NULL,
	payload TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
